name: Linux build

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: CMake version
              run: cmake --version

            - name: Create build directory
              run: mkdir build
              working-directory: ./dynamiclibrary

            - name: CMake
              run: cmake ..
              working-directory: ./dynamiclibrary/build

            - name: Run Makefile
              run: make
              working-directory: ./dynamiclibrary/build